version: "3.8"
services:
  mask2anomaly:
    image: phatli/mask2anomaly
    stdin_open: true
    tty: true
    ipc: host
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ./
        target: /home/user/Mask2Anomaly
      - type: bind
        source: /mnt/cityscapes
        target: /home/user/Mask2Anomaly/datasets/cityscapes
    dns:
      - 8.8.8.8